@startuml
Participant "Any Actor grouped with\nSecure Node or \nSecure Application" as SecureNode
Participant "Audit Record Repository \ngrouped with \nAudit Record Forwarder" as AuditForwarder
Participant "Audit Record Repository" as AuditRepository
activate SecureNode
SecureNode -> AuditForwarder++: Record Audit Event [ITI-20]
AuditForwarder -> AuditForwarder: decide to forward
AuditForwarder -> AuditRepository: Record Audit Event [ITI-20]
deactivate AuditForwarder
deactivate SecureNode

SecureNode -> AuditRepository: Record Audit Event [ITI-20]
@enduml