@startuml
participant "Document \n Consumer" as consumer
participant "Notification \n Recipient" as recipient
participant "Subscriber" as subscriber
participant "EHR" as ehr
participant "Integrated \n Publisher/ \n Notification \n Broker" as notificationbroker
participant "Document \n Registry" as registry
participant "Document \n Repository" as repository
participant "Document \n Source" as source
note over consumer, ehr: Hospital EHR - Dept. of Labor and Delivery.
note over notificationbroker, repository: HIE
note over source: OBGYN Office EHR
source->repository++:Initial ObGyn visit summary \n Provide and Register \n [ITI-41]
repository->registry++:Register [ITI-42]
deactivate repository
deactivate registry
ehr->ehr: Future mother entered in \n system for upcoming \n labor and delivery
subscriber->notificationbroker++: Subscribe for this patient ID \n Document Metadata Subscribe \n [ITI-52]
deactivate notificationbroker
consumer->registry++: Initial Stored Query for existing document about this patient [ITI-18]
deactivate registry
consumer->repository++: Retrieve Document Set as a result of Initial Stored Query [ITI-43]
deactivate repository
source->repository++: Subsequent ObGyn visit \n summary Provide and \n Register [ITI-41]
repository->registry++: Register [ITI-42]
registry-->notificationbroker++:Internal \n interaction
notificationbroker->recipient++: Notification of new document(s) \n being available \n Document Metadata Notify [ITI-53]
recipient-->consumer++:Internal \n interaction
skinparam SequenceMessageAlign center
consumer->repository: Retrieve Document Set [ITI-43] \n as a result of the Notify [ITI-53]  
deactivate repository
deactivate registry
deactivate notificationbroker
deactivate recipient
deactivate consumer
note over consumer, source: Multiple new documents may become available, repeating these steps
ehr->ehr:Successful \n delivery
deactivate ehr
subscriber->notificationbroker++:Unsubscribe [ITI-52]
deactivate notificationbroker
@enduml