@startuml
participant "Document \n Metadata \n Publisher" as publisher
participant "Document \n Metadata \n Subscriber" as subscriber
participant "Document \n Metadata \n Notification \n Broker" as notificationbroker
participant "Document \n Metadata \n Notification \n Recipient" as recipient
subscriber->notificationbroker++:Subscribe
deactivate notificationbroker
publisher->notificationbroker++:Publish
notificationbroker->recipient++:Notify
deactivate notificationbroker
deactivate recipient
publisher->notificationbroker++:Publish
notificationbroker->recipient++:Notify
deactivate notificationbroker
deactivate recipient
@enduml