@startuml
participant "Document \n Metadata \n Subscriber \n ------------------ \n Document \n Metadata \n Notification \n Recipient" as subscriberrecipient 
participant "Document \n Consumer \n ------------------ \n XDW Content \n Consumer" as consumerXDW 
participant "Document \n Source \n (EHR)" as sourceEHR 
participant "XDW Content \n Creator" as XDWcreator 
participant "Document \n Consumer" as documentconsumer 
participant "XDW Content \n Updater" as XDWupdater 
participant "Document Source \n (HIS)" as sourceHIS 
participant "Document \n Repository" as documentrepository 
participant "Document \n Registry \n ---------------- \n Document \n Metadata \n Notification \n Broker" as registrynotificationbroker 
note over subscriberrecipient, XDWcreator: Clinician EHR
note over documentconsumer, sourceHIS: HIS  
note over documentrepository, registrynotificationbroker: Regional EHR 
XDWcreator-->sourceEHR++: Internal interaction 
skinparam SequenceMessageAlign center
sourceEHR->documentrepository++: Provide and Register Document Set-b [ITI-41] \n (WD, eReferral) 
deactivate sourceEHR 
documentrepository->registrynotificationbroker++: Register Document Set-b [ITI-42]
subscriberrecipient->registrynotificationbroker: Document Metadata Subscribe [ITI-52]\n($DocumentEntryReferenceIdList=workflow Id) 
deactivate sourceEHR 
deactivate documentrepository 
deactivate registrynotificationbroker 
XDWupdater-->sourceHIS++:Internal interaction 
sourceHIS->documentrepository++: Provide and Register \n Document Set-b [ITI-41]\n (WD, Report) 
documentrepository->registrynotificationbroker++: Register Document Set-b [ITI-42]
deactivate sourceHIS 
deactivate documentrepository 
registrynotificationbroker->subscriberrecipient++: Document Metadata Notify [ITI-53]
deactivate registrynotificationbroker 
deactivate subscriberrecipient 
consumerXDW->registrynotificationbroker++: Registry Stored Query [ITI-18] (FindDocumentsByReferenceId) 
deactivate registrynotificationbroker 
consumerXDW->documentrepository++: Retrieve Document Set-b [ITI-43]
deactivate documentrepository 
consumerXDW->registrynotificationbroker++: Registry Stored Query [ITI-18] (GetDocuments) 
deactivate registrynotificationbroker 
consumerXDW->documentrepository++: Retrieve Document Set-b [ITI-43]
deactivate documentrepository
@enduml