@startuml
participant "Document \n Metadata \n Subscriber" as subscriber
participant "Document \n Metadata \n Notification \n Recipient" as recipient
participant "Document \n Consumer" as consumer
participant "Document \n Source" as source
participant "Integrated \n Publisher/ \n Notification \n Broker" as notificationbroker
participant "XDS \n Document \n Registry" as registry
participant "XDS \n Document \n Repository" as repository
note over subscriber, consumer: Clinician EMR
note over source: Laboratory \n Information \n System
note over notificationbroker, repository: RHIO
skinparam SequenceMessageAlign center
subscriber->notificationbroker++:Document Metadata Subscribe [ITI-52] \n Parameters: PatientID=Mr.White, intendedRecipient=Dr.Brown
deactivate notificationbroker
skinparam SequenceMessageAlign center
source->repository++:Provide and Register Document Set-b [ITI-41] \n metadata: submissionSet.intendedRecipient=Dr.Brown
repository->registry++:Register Document Set-b [ITI-42]
registry-->notificationbroker++:Internal interaction
notificationbroker->recipient:Document Metadata Notify [ITI-53]
deactivate notificationbroker
recipient-->consumer:Internal interaction
consumer->registry:Registry Stored Query [ITI-18]
deactivate registry
consumer->repository: Retrieve Document Set-b [ITI-43]
deactivate repository
deactivate recipient
deactivate consumer
@enduml